import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertTriangle, Bell } from 'lucide-react';
import { alerts } from '../data/mockData';
import { StatusBadge, RiskBadge } from '../components/ui';

export default function Alerts() {
  const navigate = useNavigate();
  const [filter, setFilter] = useState('All');
  const filters = ['All', 'Critical', 'High', 'Medium', 'Low'];

  const filtered = alerts.filter(a => filter === 'All' || a.priority === filter);

  return (
    <div className="p-6 space-y-6 max-w-screen-xl mx-auto">
      <div>
        <h1 className="text-2xl font-bold text-slate-800">AI Alerts</h1>
        <p className="text-slate-500 text-sm mt-1">Active leak risk alerts generated by the predictive model.</p>
      </div>

      <div className="flex gap-2 flex-wrap">
        {filters.map(f => (
          <button key={f} onClick={() => setFilter(f)}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${filter === f ? 'bg-sky-500 text-white' : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'}`}>
            {f}
          </button>
        ))}
      </div>

      <div className="space-y-3">
        {filtered.map(a => (
          <div key={a.id} className="card hover:shadow-md transition-shadow cursor-pointer"
            onClick={() => navigate(`/alerts/${a.id}`)}>
            <div className="flex items-start justify-between gap-4">
              <div className="flex items-start gap-3">
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0
                  ${a.priority === 'Critical' ? 'bg-red-100' : a.priority === 'High' ? 'bg-orange-100' : 'bg-amber-100'}`}>
                  <AlertTriangle size={18} className={
                    a.priority === 'Critical' ? 'text-red-600' : a.priority === 'High' ? 'text-orange-600' : 'text-amber-600'
                  } />
                </div>
                <div>
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-semibold text-slate-800">{a.pipeline} — {a.zone}</span>
                    <StatusBadge status={a.priority} />
                    <RiskBadge risk={a.risk} />
                  </div>
                  <p className="text-sm text-slate-600 mt-1">{a.prediction}</p>
                  <p className="text-xs text-slate-500 mt-0.5">Reason: {a.reason}</p>
                </div>
              </div>
              <div className="text-right flex-shrink-0">
                <div className="text-xs text-slate-500">{a.time}</div>
                <button className="mt-2 text-xs text-sky-500 hover:underline font-medium">View Details →</button>
              </div>
            </div>
          </div>
        ))}
        {filtered.length === 0 && (
          <div className="card text-center py-16">
            <Bell size={40} className="text-slate-300 mx-auto mb-3" />
            <p className="font-medium text-slate-600">No active alerts</p>
            <p className="text-sm text-slate-500 mt-1">All monitored pipelines are currently within configured thresholds.</p>
          </div>
        )}
      </div>
    </div>
  );
}
